apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingressroute
  namespace: apps
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`vm.apps.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: whoami-svc
          port: 80
      middlewares:
        - name: rename-headers # header重命名
        - name: auth-errors    # 鉴权失败重定向中间件
        - name: forward-auth   # 鉴权中间件

    - match: Host(`vm.apps.com`) && PathPrefix(`/v2/user/login`)
      kind: Rule
      services:
        - name: whoami-svc
          port: 80
      middlewares:
        - name: login-interceptor  # 登录拦截中间件

