kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller  # 指定serviceAccount以获得其他ns的访问权限
      containers:
        - name: traefik-ingress-controller
          image: traefik:v2.11.0
          imagePullPolicy: IfNotPresent
          ports:  # 端口映射到host
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 8080
              hostPort: 18080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: traefik-config
              mountPath: /etc/traefik/traefik.toml
              subPath: traefik.toml
#            - name: traefik-config-dynamic
#              mountPath: /etc/traefik/dynamic.toml
#              subPath: dynamic.toml
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-config
        - name: traefik-config-dynamic
          configMap:
            name: traefik-config-dynamic
