# 鉴权中间件
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: apps
spec:
  forwardAuth:
<<<<<<< HEAD
    address: "http://10.41.120.57:8082/v2/authentication"  # 认证转发地址
    trustForwardHeader: true                               # 信任全部X-Forwarded-* header
=======
    address: "https://www.baidu.com"  # 认证转发地址
    trustForwardHeader: true          # 信任全部X-Forwarded-* header
    authResponseHeaders:
      - X-Kuas-User-Id
>>>>>>> dev

---
# 鉴权失败的重定向
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-errors
  namespace: apps
spec:
  errors:
    status:
      - 401-403
    service:
      name: whoami-svc
      port: 80
<<<<<<< HEAD
    query: "/test/sign_in"
=======
    query: "/test/sign_in?{query}"
>>>>>>> dev
